version: '2.4'

services:
  redis:
    image: 'redis:4.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
    healthcheck:
      test: 'redis-cli ping'

  db:
    image: 'mongo'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - 'db:/var/lib/db/data'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
# TODO change command to use nodemon for development
# Currently the api command will use the npm scripts to build the dist dir
# where the compiled JS will be
  api:
    build: .
    command: npm run dev
    env_file: '.env'
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - '5000:5000'
    depends_on:
      redis:
        condition: 'service_healthy'
      db:
        condition: 'service_healthy'
    volumes:
      - '.:/app'

volumes:
  redis: {}
  db: {}