version: '2'

services:
  redis:
    image: 'redis:4.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
    healthcheck:
      test: 'redis-cli ping'

  db:
    image: 'mongo'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - 'db:/var/lib/db/data'
# TODO change command to use nodemon for development
  web:
    build: .
    env_file: '.env'
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - '5000:5000'
    depends_on:
      redis:
        condition: 'service_healthy'
      - 'db'
    volumes:
      - '.:/app'

volumes:
  redis: {}
  db: {}